language: node_js
node_js: 
    - '6.10.3'

# test sonar

addons:
  sonarcloud:
    organization: "$SONAR_ORG"
    token:
      secure: "$SONAR_TOKEN"

# Travis-CI Caching
cache:
  directories:
    - node_modules


# S: Build Lifecycle
install:
  - npm install
  #- npm install --registry=https://registry.npm.taobao.org

before_script:

script:
  - npm run build
  - sonar-scanner

after_script:
  - cd ./dist
  - git init
  - git config user.name "${U_name}"
  - git config user.email "${U_email}"
  - git add .
  - git commit -m "Update tools"
  - git push --force --quiet "https://${git_token}@${git_add}" master:master
# E: Build LifeCycle

branches:
  only:
    - master
env:
 global:
   #- GH_REF: github.com/yimogit/metools.git
